### ISSUE TITLE
Lower and upper bounds not respected during initial optimization - easyGParetoptim

### ISSUE THREAD

**Issue by mcgregorian1** [mbinois/GPareto#4]
I've noticed that the lower and upper bounds supplied to `easyGParetoptim` are not used to constrain the values of the `design.init`. I will show what I mean below.

These are my initial parameters. As a reminder, also here are the default values for the function
```
Default: easyGParetoptim <- function (fn, ..., cheapfn = NULL, budget, lower, upper, par=NULL, value=NULL, noise.var=NULL,
                             control=list(method="SMS", trace=1, inneroptim="pso", maxit=100, seed=42), ncores = 1){}

budget = 100
lower = c(65,0.1)
upper = c(90,0.8)
par=NULL
value=NULL
noise.var=NULL
control=list(method="EMI", trace=1, inneroptim="genoud", maxit=1000) 
```

I then run part of the source code of `easyGParetoptim`
```
if (is.null(control$method)) control$method <- "SMS"
if (is.null(control$trace)) control$trace   <- 2
if (is.null(control$inneroptim))  control$inneroptim <- "pso"
if (is.null(control$maxit)) control$maxit   <- 100
if (is.null(control$seed)) control$seed   <- 42
if (is.null(control$refPoint)) control$refPoint   <- NULL
if (is.null(control$distance)) control$distance <- "euclidean"
if (is.null(control$threshold)) control$threshold <- 1e-5

fn <- match.fun(fn)
d <- length(lower)

if (length(lower) != length(upper)) {
  cat("Bound values lower and upper are not consistent. Both should be vectors of size d.")
  return(NULL)
}

if (!is.null(par)) {
  design.init <- data.frame(x=par) #, ncol=d, byrow=TRUE)
  temp <- dim(design.init)
  
  if (temp[2] != d) {
    cat("Bound values (lower and upper) and initial DOE (par) are not consistent. \n 
          lower and upper should be vectors of size d and \n 
          par either a matrix with d columns or a data frame of d variables.")
    return(NULL)
  }
  n.init <- temp[1]
} else {
  n.init <- max(4*d, round(budget/3))
  design.init <- data.frame(x=lower + (upper-lower)*DiceDesign::maximinESE_LHS(DiceDesign::lhsDesign(n.init, d, seed=control$seed)$design)$design)
}
```

What I am not understanding is the creation of `design.init` here. When I run this code with my defined parameters, I get the following for `design.init`, which is static because `seed` is always set to be 42. Columns `x.1` and `x.2` are assumed to be my two parameters, because `design.init` is then passed to my objective function in the next line of code (below the table here). However, this is a problem because my first parameter explicitly has a bound of c(65,90) yet column `x.1` clearly has values <65. Similarly, my second parameter has a bound of c(0.1, 0.8), yet column `x.2` has values > 1. When assessing these initial parameterizations, my objective function retains some of these as non-dominated.

Why are these values not constrained before passing to the objective function?
```
> design.init
          x.1        x.2
1  76.0696149  0.7520375
2   0.2557608 65.7280784
3  77.3340059  0.6126351
4   0.7398423 84.4342816
5  69.5949453  0.2773338
6   0.6285544 72.5977526
7  79.3049338  0.1493053
8   0.1248087 73.4183675
9  66.5796924  0.5959640
10  0.6830319 80.3900229
11 73.7310628  0.4823795
12  0.5123566 70.8080097
13 69.1522000  0.4302356
14  0.3092646 74.5609400
15 74.4982630  0.1315125
16  0.7790235 71.8889383
17 88.5575520  0.1847647
18  0.4735411 79.7223573
19 65.4108017  0.4688411
20  0.5393849 85.4675627
21 67.8367963  0.1901771
22  0.3303910 84.8791331
23 84.1389482  0.7066988
24  0.5742660 81.9111539
25 84.7424132  0.2106277
26  0.5467893 89.6698700
27 74.9198954  0.2440800
28  0.5890101 77.1533511
29 87.3886594  0.7786323
30  0.4221897 75.4763149
31 71.0771012  0.5658727
32  0.6995055 75.7199320
33 68.2537388  0.7323445

if (!is.null(par) && !is.null(value)) {
  obs.init <- as.matrix(value)
  if (nrow(obs.init) != n.init) {
    cat("Initial DOE (par) and objective (value) are not consistent.")
    return(NULL)
  }
} else {
  obs.init <- apply(design.init, 1, fn)
}
```

**Comment by mbinois** [comment]
Thanks for reporting this bug, it should be corrected now. 
Most of the time the black-box is taken is [0,1]^D to avoid scaling issues in GP fitting, so it didn't show up (adding the lower vector to the lhs matrix was the cause, since lower was repeated column-wise and not row-wise).  The seed is fixed for reproducibility, but feel free to change it via control$seed.
Cheers

**Comment by mcgregorian1** [comment]
Thank you! I can confirm it works.

However, one more suggestion - I think there needs to be `DiceDesign::` ahead of the `maximin` and `lhsDesign` functions, because `library(GPareto)` does not inherently load `DiceDesign`.
- Thus I believe the full code should be

```
design.init <- data.frame(x = matrix(lower, nrow = n.init, ncol = d, byrow = TRUE) + DiceDesign::maximinESE_LHS(DiceDesign::lhsDesign(n.init, d, seed=control$seed)$design)$design %*% diag((upper-lower)))
```

**Comment by mbinois** [comment]
Great, thanks for confirming.
As for DiceDesign, it is imported by GPareto, but not loaded (in order not to add it automatically to the workspace). If you use these lines outside of the package, library(GPareto) is indeed needed.
